#--------
# converted from: assets/scene/alleyway.yaml
id = "<scene name>"
INIT_ZOOM = 1
CAMERASLACK = 100
DRAW_LAYERS = ['background', 'foreground', 'hud']

[[hud]]
id = "hearts"
type = "Decal"
image = "./assets/block/hud_element.png"
start = [0, 0]
mask = ""


[[background]]
id = "alleyway map"
type = "Decal"
image = "./assets/scene/alleyway/map.png"
mask = "./assets/scene/alleyway/foreground.png"
groups = ['solid']


[[foreground]]
id = "alley_exit"
type = "Edge"
image = "./assets/block/block.png"
mask = "./assets/block/block.png"
start = [1138, 167]
scale = 2.5
scene_path = "./assets/scene/mansion_yard.yaml"
exit_dir = "LEFT"

