#--------
# converted from: assets/scene/boss_room.yaml
id = "<scene name>"
INIT_ZOOM = 1
CAMERASLACK = 100
DRAW_LAYERS = ['background', 'foreground', 'hud']
hud = ""

[[background]]
id = "boss room"
type = "Decal"
image = "./assets/scene/boss_room/map.png"
mask = "./assets/scene/boss_room/foreground.png"
groups = ['solid']


[[foreground]]
id = "grate exit"
type = "Edge"
image = "./assets/block/block.png"
mask = "./assets/block/block.png"
start = [117, 117]
scale = 1
scene_path = "./assets/scene/mansion_yard.yaml"
exit_dir = "DOWN"

[[foreground]]
id = "doorway exit"
type = "Edge"
image = "./assets/block/block.png"
mask = "./assets/block/block.png"
start = [1132, 1033]
scale = 1
scene_path = "./assets/scene/corridor.yaml"
exit_dir = "LEFT"

