#--------
# converted from: assets/scene/forest.yaml
id = "forest"
DRAW_LAYERS = ['background', 'foreground', 'hud']
INIT_ZOOM = 1
CAMERASLACK = 100

[[background]]
id = "dungeon_tile"
type = "Decal"
image = "./assets/scene/forest/map.png"
mask = "./assets/scene/forest/foreground.png"
groups = ['solid']


[[foreground]]
id = "forest_red_castle_valley_connection"
type = "Edge"
image = "./assets/block/block.png"
mask = "./assets/block/block.png"
start = [325, 575]
scale = 2.5
scene_path = "./assets/scene/red_castle_valley.yaml"
exit_dir = "LEFT"

