#--------
# converted from: assets/scene/mansion_yard.yaml
id = "mansion yard"
INIT_ZOOM = 1
CAMERASLACK = 100
DRAW_LAYERS = ['background', 'foreground', 'hud']

[[background]]
id = "mansion yard map"
type = "Decal"
image = "./assets/scene/mansion_yard/background.png"
mask = "./assets/scene/mansion_yard/foreground.png"
groups = ['solid']


[[foreground]]
id = "bridge_exit"
type = "Edge"
image = "./assets/block/block.png"
mask = "./assets/block/block.png"
start = [860, 1969]
scale = 2.5
scene_path = "./assets/scene/red_castle_valley.yaml"
exit_dir = "UP"

[[foreground]]
id = "alley_exit"
type = "Edge"
image = "./assets/block/block.png"
mask = "./assets/block/block.png"
start = [688, 146]
scale = 2.5
scene_path = "./assets/scene/alleyway.yaml"
exit_dir = "RIGHT"

[[foreground]]
id = "statue_exit"
type = "Edge"
image = "./assets/block/block.png"
mask = "./assets/block/block.png"
start = [1058, 222]
scale = 1
scene_path = "./assets/scene/corridor.yaml"
exit_dir = "RIGHT"

[[foreground]]
id = "grate exit"
type = "Edge"
image = "./assets/block/block.png"
mask = "./assets/block/block.png"
start = [89, 712]
scale = 1
scene_path = "./assets/scene/boss_room.yaml"
exit_dir = "RIGHT"

