#--------
# converted from: assets/scene/scene_template.yaml
id = "<scene name>"
INIT_ZOOM = 1
CAMERASLACK = 100
DRAW_LAYERS = ['background', 'foreground', 'hud']

[[background]]
id = "<unique ID 2>"
type = "Decal"
image = "<image path>"
mask = "<mask image path>"
groups = ['solid']


[[foreground]]
id = "<unique ID 2>"
type = "Decal <or subclass>"
yaml = "<path to yaml data>"
start = [700, 900]

[[foreground]]
id = "<unique ID 3>"
type = "Edge"
image = "<image path>"
mask = "<image path>"
start = [845, -80]
scale = 2.5
scene_path = "<new scene path>"
exit_dir = "<direction of exit into this scene>"

