#--------
# converted from: assets/actor/ossifrage.yaml
image = "./assets/actor/ossifrage/bird_character_base.png"
mask = "./assets/actor/ossifrage/bird_character_base.png"
groups = ['foe']

[[animations]]
id = "null"
image = "./assets/block/null.png"
repeat = true
key_frame_size = [32, 32]
key_frame_times = [1]

[[animations]]
id = "stand"
image = "./assets/actor/ossifrage/ossifrage_stand.png"
repeat = true
key_frame_size = [32, 32]
key_frame_times = [1]

[[animations]]
id = "walk"
image = "./assets/actor/ossifrage/ossifrage_walk.png"
repeat = true
key_frame_size = [32, 32]
key_frame_times = [50]

[[animations]]
id = "damage"
image = "./assets/actor/ossifrage/ossifrage_damage.png"
repeat = false
key_frame_size = [32, 32]
key_frame_times = [50]

